### ISSUE TITLE
Set an array of schemas

### ISSUE THREAD

**Issue by estrada9166** [ardatan/graphql-toolkit#11]
It's possible to set an array of schemas? something like [this](https://github.com/okgrow/merge-graphql-schemas#manually-import-each-type)

Thanks!

**Comment by dotansimha** [comment]
@estrada9166 why not? 
Please take a loot at the epoxy API: https://github.com/ardatan/graphql-toolkit/blob/master/src/epoxy/schema-mergers/merge-schema.ts#L25 , it accept an array.
