### ISSUE TITLE
Wrong windows path resolution

### ISSUE THREAD

**Issue by Aliaksei-Martsinkevich** [ardatan/graphql-toolkit#167]
When loading schema from relative path like `schema.js` on Windows machine, it resolved into `C:\abs\path\to\schema.js`. [here](https://github.com/ardatan/graphql-toolkit/blob/master/src/loaders/schema/schema-from-export.ts#L43). When this string is passed to `require`, it leads to following `\a`, `\p` and so on are processed as escape character, and `\p` = `p`. So path becomes `C:abspathtoschema.js`, which cannot be resolved, obviously.

**Comment by ardatan** [comment]
Available since 0.4.0
