### ISSUE TITLE
Inject custom fetcher for URL loaders

### ISSUE THREAD

**Issue by jlkiri** [ardatan/graphql-toolkit#180]
As far as I can see, with new release, `graphql-toolkit` now uses `cross-fetch` library instead of `request` for making http requests. This (indirectly) makes it impossible to use newer versions of `graphql-code-generator` behind a proxy, because `cross-fetch` does not respect the HTTP_PROXY environment variable.

It would be nice if `graphql-toolkit` allowed for injection of custom fetching functions.

**Comment by ardatan** [comment]
Until this gets solved, does this work for you?
https://github.com/gajus/global-agent

**Comment by kamilkisiela** [comment]
Related #190

**Comment by kamilkisiela** [comment]
`v0.5.0` is now out

**Comment by jlkiri** [comment]
Thank you!
