### ISSUE TITLE
problem loading complete schema from gql literal

### ISSUE THREAD

**Issue by jsphweid** [ardatan/graphql-toolkit#204]
consider a file like this:
```typescript
import gql from 'graphql-tag';

import * as OtherTypes from './graphql-tag';

export const typeDefs = gql`
  type Review {
    b: String
  }

  ${OtherTypes.typeDefs}
`;
```

graphql-toolkit will not parse this correctly. It will pick up on the Review type but nothing from the import. The way to get this to work would be to move Review to another file and import both like

```typescript
export const typeDefs = gql`
  ${OtherTypes.typeDefs}
  ${NewFileWithReview.typeDefs}
`;
```

It ain't that big of a deal but it seems like this should work. I forked to write a test showing the failure but didn't architect a solution yet. https://github.com/ardatan/graphql-toolkit/compare/master...jsphweid:master

Let me know what you think about it. It looks like it happens here: https://github.com/ardatan/graphql-toolkit/blob/03d527370bb1e0babb68a597f1e618b38e13d370/src/loaders/load-from-code-file.ts#L93 this comes back with truthy info and ignores the load from export.

**Comment by dotansimha** [comment]
Hi @jsphweid ! 
The load-from-ast loader is not evaluating your file, and only loads is as string, without running `require`. It's an optimization that intended to reduce file loading and file executions.  
You can use add your other files and load them as well: `loadTypedefs(['./schema.ts', './graphql-tag.ts'])`
