### ISSUE TITLE
Loading schema from type definitions passes a promise as the source argument to parse from graphql-js

### ISSUE THREAD

**Issue by dimitar-nikovski** [ardatan/graphql-toolkit#25]
Hi,

I am attempting to generate types using `graphql-code-generator` and a .graphql file.

This calls: => the respective loader from this package => and then  when `extractDocumentStringFromCodeFile `is called [here](https://github.com/ardatan/graphql-toolkit/blob/75d576c236432cbc408dc076889861ef5d2f3410/src/loaders/schema/schema-from-typedefs.ts#L27) it returns a Promise, whereas if it were to return the content read using `readFileSync `from the file from the same `loadSchemaFile ` function, it would have returned a `string` result synchronously.

The pending promise is then passed to graphql's parse [here](https://github.com/graphql/graphql-js/blob/7786a2524b759401142be1eb0999df4a55f1672b/src/language/parser.js#L125) which causes it tor throw a validation error "Must provide Source. Received: {}".

Happy to submit a PR in the next couple of days if you could recommend a workaround?

**Comment by kamilkisiela** [comment]
@dimitar-nikovski Could you create a test for it?

I tried here https://github.com/ardatan/graphql-toolkit/pull/31 but it seems to work fine
