### ISSUE TITLE
Load schema from introspection assumes that schemaOptions is non-null 

### ISSUE THREAD

**Issue by mikejewell** [ardatan/graphql-toolkit#27]
The following line fails if schemaOptions is 'null' (Cannot read property 'headers' of null) - it could be fixed by the caller, but should probably be handled in here too:

https://github.com/ardatan/graphql-toolkit/blob/master/src/loaders/schema/introspection-from-url.ts#L18

**Comment by dotansimha** [comment]
Fixed in 0.2.1!
