### ISSUE TITLE
broken on Ubuntu/bionic

### ISSUE THREAD

**Issue by svogl** [ardatan/graphql-toolkit#272]
Ubuntu/bionic still uses nodejs 8.11 which does not support `for await`
This line breaks our build environment which indirectly depends on this package:

https://github.com/ardatan/graphql-toolkit/blob/d16ead52872c2dbe83408b3c5dd11202900e0bec/src/loaders/load-typedefs.ts#L138

**Comment by ardatan** [comment]
It is the same issue which has been fixed already;
https://github.com/ardatan/graphql-toolkit/issues/259
So if you want to use it before the release, you can use canary version;
`0.5.17-d16ead5.0`

**Comment by svogl** [comment]
great -- didn't see this fix yet. thanks!
Simon
