### ISSUE TITLE
Validation doesn't work for schemas with extended types

### ISSUE THREAD

**Issue by Kujawadl** [ardatan/graphql-toolkit#346]
Our project uses @dotansimha's graphql-code-generator, and encountered a breaking change when upgrading to the latest version. I narrowed it down to a single commit that upgraded this package from 0.5.12 to 0.5.13, and within those commits, I found 51fc38a to be the culprit.

The bug only happens with schemas that use the `extend` keyword (see attached CodeSandbox at the bottom for an example). Basically, graphql-toolkit's validation function is failing, because for some reason it's only viewing the type as containing the fields it was initially declared with, and not also the types it was extended with.

As a workaround, I found that I was able to get the schema to merge all those definitions by wrapping it with a `makeRemoteExecutableSchema` call. I'd be fine with that workaround, but perhaps it would be better to make that call in the library somewhere before the validations are run? I don't know. At the very least I'd like to document it for anybody else who has the same issue going forward.

[CodeSandbox Reproduction](https://codesandbox.io/s/apollo-server-3uc2k)
[Schema AST without makeRemoteExecutableSchema wrapper](https://3uc2k.sse.codesandbox.io/allTypesAst)
[Schema AST with makeRemoteExecutableSchema wrapper](https://3uc2k.sse.codesandbox.io/remoteAllTypesAst)

(Not necessarily helpful to this issue, but helpful to those who search Google for the error message in the future: The specific error message I got was `GraphQLDocumentError: Cannot query field "addItemsToCart" on type "Mutation".`, repeated for every field in the `Mutation` and `Query` types.)

**Comment by bretep** [comment]
Same issue here.

**Comment by ardatan** [comment]
Available in 0.7.5!
