### ISSUE TITLE
Commit 6d99f92 uses globby which breaks file scanning in Next.js apps

### ISSUE THREAD

**Issue by msheakoski** [ardatan/graphql-toolkit#370]
Commit 6d99f92 introduced a change where `glob` was switched to `globby` in [file-scanner.ts](https://github.com/ardatan/graphql-toolkit/commit/6d99f92441c436ecbebc98270bff89b6c82c27d3#diff-dd23da73301e6a7aeb6e42892a935fba). Because [globby skips folders with symbols in it's name](https://github.com/sindresorhus/globby/issues/81), scanning for `gql` fails when it is located inside of files containing brackets such as `src/pages/[category]/[product].tsx` which are used in nearly all [Next.js apps for routing](https://nextjs.org/docs#dynamic-routing).

Related issue: dotansimha/graphql-code-generator#3058

**Comment by ardatan** [comment]
It is related to document loader in core not `file-scanner`. But you're right, this is a bug. We're currently investigating it.

**Comment by ardatan** [comment]
Fixed in v0.8.1
