### ISSUE TITLE
Unable to parse test files with a glob expression

### ISSUE THREAD

**Issue by geotry** [ardatan/graphql-toolkit#391]
Since version 1.9.X of graphql-codegen I'm unable to parse my graphql documents located in my test files (ending by `.spec.ts`).

I found in the source code this line causing these files to be ignored:
https://github.com/ardatan/graphql-toolkit/blob/155dcb26ee6ed3f5d80805f2ecaf38354d816317/packages/core/src/load-typedefs.ts#L169

It works if I don't use a glob expression and directly point my file.
What is the reason behind this? Because it can easily done by the glob expression itself.

**Comment by ardatan** [comment]
If you use `yarn`, you can try it by using `resolutions` field in package.json to test the fix with the following version?
`1.10.1-alpha-2faa59c0.4+2faa59c0`

**Comment by geotry** [comment]
I tested using version `0.8.2-alpha-d68e52d.1` of `@graphql-toolkit/core` in `resolutions` (wasn't sure which package you were mentionning), and it worked!
Thank you 👍
