### ISSUE TITLE
How to pass options to the loaders?

### ISSUE THREAD

**Issue by esamattis** [ardatan/graphql-toolkit#420]
Sorry about question issue but I don't know where else to ask.

I'd like to use `loadSchema` with the `UrlLoader` but I need to pass in authentication headers.

In an earlier version it was possible to do like this

```ts
loadSchema(options.graphqlEndpoint, {
        headers: {
            authorization: "***",
        },
    });
```

But now with loaders I'm not able to figure out how to do it. By looking at the TypeScript types the options go to `loader.load(pointer, options)` but how to pass it to them as load schema takes loader instances?

Thanks.

**Comment by ardatan** [comment]
It should work in the same way;
```ts
import { loadSchema } from '@graphql-toolkit/core';
import { UrlLoader } from '@graphql-toolkit/url-loader';

const yourSchema = await loadSchema(options.graphqlEndpoint, {
        loaders: [
           new UrlLoader(),
        ], 
        headers: {
            authorization: "***",
        },
    });
```

**Comment by esamattis** [comment]
Ah right! My intuition was that the loader configuration would have had to be moved out of the `loadSchema` too with the loaders. Thanks!

**Comment by jjangga0214** [comment]
@ardatan I think passing header is not uncommon, but docs does not mention that it's possible by [`LoadSchemaOptions`](https://github.com/ardatan/graphql-tools/blob/master/packages/load/src/schema.ts#L7).
What if docs explicitly mention it as an example usage?
