### ISSUE TITLE
Unknown directive "deprecated" after updating to v0.9.1+

### ISSUE THREAD

**Issue by alfaproject** [ardatan/graphql-toolkit#437]
I've been getting this error in any new version after 0.9.0. In other words, v0.9.0 is the last version that works for my schema merging needs.

The only method I use from this package is `mergeTypeDefs` so that's the one that stopped working.

Is there anything new that I need to do to support `@deprecated` directive? I wasn't expecting it to break in a patch release. ):

**Comment by ardatan** [comment]
@alfaproject Could you share a reproduction repo? Thanks!

**Comment by ardatan** [comment]
I'm closing it now. If the problem persists in the latest version, feel free to open a new issue with a reproduction :)
