### ISSUE TITLE
Unable to merge GraphQL type changed type from '[Type!]' to '[Type!]!'

### ISSUE THREAD

**Issue by Fi1osof** [ardatan/graphql-toolkit#472]
It should not prevent change from not-required to required. 
From required to not-required - it's not allowed in GraphQL. But from not-required to required - allowed.

Finded here: https://github.com/ardatan/graphql-toolkit/blob/5071524af2d74318085c8f6c1390f96421da1f75/packages/schema-merging/src/typedefs-mergers/fields.ts#L73-L83

**Comment by ardatan** [comment]
@dotansimha @kamilkisiela What do you think?

**Comment by dotansimha** [comment]
I think this is a valid change, @kamilkisiela it's the same in graphql-inspector, right?

**Comment by kamilkisiela** [comment]
<img width="1161" alt="Zrzut ekranu 2020-03-11 o 09 53 12" src="https://user-images.githubusercontent.com/8167190/76399418-d9d70d00-637e-11ea-9722-4ec57a2e890a.png">

Inspector says "green" and I agree.

The consumer (client-side app for example) is prepared for nullable values so it accept `null` and `object` so if we remove `null` from responses then nothing happens, it still works.

**Comment by kamilkisiela** [comment]
#485
