### ISSUE TITLE
Breaks on React-Native due to dependencies on Node standard library

### ISSUE THREAD

**Issue by mrflip** [ardatan/graphql-toolkit#473]
The library does not work in my react-native app, because of dependencies on libs that import core Node.js libs -- `path` and `fs`.

```
The package at "node_modules/resolve-from/index.js" attempted to import the Node standard library module "path". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo

The package at "node_modules/globby/index.js" attempted to import the Node standard library module "fs". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
```

My package.json: https://gist.github.com/mrflip/40ab952f3aa6c49d003e753c5a974441

Is there a straightforward way to patch this?

**Comment by ardatan** [comment]
@mrflip GraphQL File Loader uses File System API of NodeJS so it is not compatible to Non-Node environments. You can try something like this;
https://www.apollographql.com/docs/react/integrations/webpack/#react-native
