### ISSUE TITLE
Difficult to know what file cause an error inside `loadDocuments`

### ISSUE THREAD

**Issue by ricokahler** [ardatan/graphql-toolkit#476]
Hi there 👋

I'm a maintainer of `gatsby-plugin-ts` and I'm trying to improve the experience of crashes when code gen fails.

Downsteam, [we use `loadDocuments` with doc glob](https://github.com/d4rekanguok/gatsby-typescript/blob/002881e4f2529512d58a4db4a131ce96fc58874f/packages/gatsby-plugin-graphql-codegen/src/graphql-codegen.config.ts#L40-L44) to load nested queries.

If there is an error that occurs inside of a file (e.g. an graphql syntax error) then the error message we propagate looks something like this:

![image](https://user-images.githubusercontent.com/10551026/75365598-68319600-588b-11ea-8207-79ba4169b04d.png)

…which isn't very helpful if you don't know what file caused that issue.

---

I think we can solved this pretty easily by modifying the error message to include the file being loaded. I'll send you a 1 line PR for this.

Thanks!

**Comment by ardatan** [comment]
Available in v0.9.8 !!!
