### ISSUE TITLE
Publish new version of `@graphql-toolkit/graphql-tag-pluck`

### ISSUE THREAD

**Issue by SimenB** [ardatan/graphql-toolkit#509]
It has updated to Babel 7.9, meaning it supports newer TS features like `import type`.

**Comment by ardatan** [comment]
You can use canary version until we release new version
`@graphql-toolkit/graphql-tag-pluck => 0.9.10-alpha-359bb7b.9+359bb7b`

**Comment by ardatan** [comment]
Available in 0.9.10!

**Comment by SimenB** [comment]
thanks!

>You can use canary version until we release new version

I needed it via `graphql-code-generator` which locks down dependencies, so I needed to use `resolutions` regardless to avoid syntax errors

**Comment by ardatan** [comment]
There is another canary version on codegen that uses new graphql-toolkit;
https://github.com/dotansimha/graphql-code-generator/runs/536219017

**Comment by SimenB** [comment]
👍
