### ISSUE TITLE
Add an 'extractFieldPaths' method to extract the set of fields from a document?

### ISSUE THREAD

**Issue by magicmark** [ardatan/graphql-toolkit#582]
e.g. given an SDL file and the following query:

```graphql
query GET_BUSINESS($BizId: String) {
    business(id: $BizId) {
        name
        location {
            city
        }
    }
}
```

`extractFieldPaths` would return the following:

```
["Query.business", "Business.name", "Business.location", "BusinessLocation.city"]
```

You can already do this at runtime inside a graphql server, but I couldn't find anything that lets you statically extract this - so I wrote this!

https://github.com/sharkcore/graphql-document-tools#extractfieldpaths

Is this something the maintainers of graphql-toolkit would be interested in moving to here?

**Comment by ardatan** [comment]
Of course, that looks awesome!

**Comment by ardatan** [comment]
Feel free to submit a PR with this great feature! Closing this issue for now.
