### ISSUE TITLE
Enhancement: Warn when SchemaFromExport finds a matching file, but doesn't export the schema in the right way.

### ISSUE THREAD

**Issue by koenpunt** [ardatan/graphql-toolkit#83]
When trying to use a `.ts` file for loading the schema I found it was very difficult to see why it was not working.

Initially this was because I didn't add `ts-node` to the `require` array. But the error just showed me that the glob wasn't matching any files, which was confusing.
Before knowing I needed the require, I tried changing the file to export a function, instead of the schema directly.
When I then did add the require of `ts-node`, it still showed me the same "glob not matching" error.

I think it would help to show a warning or error when a file is found that doesn't export the schema in the right way.

**Comment by darkbasic** [comment]
Can you please upload the faulty repo along with the glob pattern you're using?

**Comment by darkbasic** [comment]
Btw, are you using 0.2.9 right?

**Comment by koenpunt** [comment]
There isn't really a faulty repo. I experienced the behavior through `graphql-code-generator`, and while stepping through the code to figure out why my files were not being loaded, I noticed that it was actually finding my ts file, but then skipped it because it wasn't exporting the schema correctly.

I've created a PR with where I think a warning should be triggered; https://github.com/ardatan/graphql-toolkit/pull/87

**Comment by darkbasic** [comment]
Please see me comment on your PR.
I need to understand the context of what you are trying to achieve and how do you expect it to behave.
An repro would help alot to let me understand what's you issue.
